# Lab 1

In [1]:
from __future__ import print_function
import torch
import os
import random
import numpy as np
import argparse
import scipy.io as sio
import math

import torch.nn as nn
import torch.nn.init as init
import torch.optim as optim
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
from torch.autograd import Variable
import torch.nn.parallel

## 1.1 Tensors

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
type(x_data)

torch.Tensor

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
type(x_np)

torch.Tensor

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [6]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.2725, 0.9603],
        [0.5393, 0.7805]]) 



In [7]:
# shapes
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [8]:
rand_tensor.shape

torch.Size([2, 3])

In [9]:
# shapes
shape = (2,3,4)
rand_tensor = torch.rand(shape)

In [10]:
print(rand_tensor)

tensor([[[0.8446, 0.7858, 0.0075, 0.3817],
         [0.2382, 0.8923, 0.7469, 0.4160],
         [0.4269, 0.2646, 0.4014, 0.4053]],

        [[0.1034, 0.4249, 0.6453, 0.7485],
         [0.7507, 0.3386, 0.5691, 0.1645],
         [0.9479, 0.6755, 0.6040, 0.5971]]])


In [11]:
rand_tensor.shape[1]

3

In [12]:
# tensor operations
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [14]:
# matrix multiplication
a = torch.ones((1,4))
b = torch.ones((4,4))
c = torch.mm(a,b)
print(c)

tensor([[4., 4., 4., 4.]])


In [15]:
# matrix multiplication
a = torch.ones((4,))
b = torch.ones((4,4))

In [16]:
torch.matmul(a,b)

tensor([4., 4., 4., 4.])

In [17]:
a.T

tensor([1., 1., 1., 1.])

In [18]:
a + a

tensor([2., 2., 2., 2.])

In [19]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## 1.2 Autograd

In [20]:
import torch, torchvision
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1,3,64,64)
labels = torch.rand(1,1000)

In [21]:
model.state_dict

<bound method Module.state_dict of ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)


In [22]:
prediction = model(data)
prediction

C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


tensor([[-6.2734e-01, -4.9248e-01, -6.4502e-01, -1.6093e+00, -8.6458e-01,
         -3.6988e-01, -5.4519e-01,  4.9333e-01,  4.5190e-01, -7.7892e-01,
         -7.3775e-01, -8.5429e-01, -3.9555e-01, -8.4611e-01, -1.1456e+00,
         -5.7683e-01, -9.7403e-01, -3.5067e-01, -6.1748e-01, -4.2001e-01,
         -1.5213e+00, -8.3086e-01, -1.4875e+00,  2.6009e-01, -9.4014e-01,
         -1.2512e+00, -7.3821e-01, -9.9055e-01, -1.0611e+00, -3.5616e-01,
         -8.9132e-01, -9.6220e-01, -5.5745e-01, -4.2756e-01, -8.2799e-02,
         -4.1557e-01,  6.8197e-01, -7.1923e-01, -4.2995e-01,  2.7831e-01,
         -6.8829e-01, -6.9781e-01, -1.1050e+00, -2.6512e-01, -6.4584e-01,
         -3.6983e-01, -7.2499e-01, -3.4136e-01, -1.0995e+00, -1.0657e+00,
         -3.6238e-01,  5.6677e-01, -3.0998e-01, -7.7016e-01, -9.3642e-02,
         -1.1471e+00, -1.4939e-01, -1.3187e+00, -6.2178e-01, -3.7587e-01,
          8.3733e-01,  3.1180e-01,  1.1813e-01,  1.1110e-01, -6.7253e-01,
         -3.8787e-01, -2.0832e-01, -4.

In [23]:
loss = (prediction - labels).sum()
loss.backward()

In [24]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [25]:
optim.step()

In [26]:
weights = [p for p in model.parameters()]
len(weights)

62

In [27]:
# differentiation in autograd
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)


In [28]:
Q = 3*a**3 - b**2

In [29]:
external_grad = torch.tensor([1.,1.])
Q.backward(gradient=external_grad)

In [30]:
a.grad

tensor([36., 81.])

In [31]:
print(9*a**2 == a.grad)

tensor([True, True])


In [32]:
print(-2*b == b.grad)

tensor([True, True])


## 1.3 Network Architecture

In [33]:
import os
import sys
# add full path of nn-train
path = "c:\\somethingsomethingsomething\\nn-train"
sys.path.append(path)

In [34]:
from train_stuff.model_loader import load

In [35]:
net = load('fc2')
print(net)

FullyConnected(
  (fc): Sequential(
    (0): Linear(in_features=784, out_features=100, bias=False)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=100, out_features=10, bias=False)
  )
)


In [36]:
weights = net.state_dict()
layers = list(net.state_dict().keys())
layers[1]
 

'fc.2.weight'

In [37]:
weights[layers[1]].shape

torch.Size([10, 100])

In [38]:
layers

['fc.0.weight', 'fc.2.weight']

In [39]:
weights

OrderedDict([('fc.0.weight',
              tensor([[ 0.0085, -0.0057,  0.0177,  ...,  0.0009,  0.0067,  0.0109],
                      [-0.0076, -0.0237, -0.0259,  ..., -0.0123,  0.0231, -0.0169],
                      [ 0.0065, -0.0035,  0.0180,  ...,  0.0212, -0.0120, -0.0120],
                      ...,
                      [-0.0304, -0.0020, -0.0016,  ...,  0.0014,  0.0276, -0.0193],
                      [-0.0342,  0.0078,  0.0146,  ...,  0.0251,  0.0339,  0.0330],
                      [ 0.0151,  0.0116, -0.0292,  ...,  0.0264, -0.0156, -0.0001]])),
             ('fc.2.weight',
              tensor([[ 6.9402e-03, -7.2924e-02, -6.9672e-02, -7.9167e-02,  6.7816e-02,
                       -1.0611e-03,  5.8461e-03, -1.6197e-02, -9.3281e-02,  2.8197e-03,
                       -2.4915e-02, -2.5322e-02, -4.2666e-02, -1.4481e-02, -6.2404e-02,
                       -9.3008e-03, -4.2019e-02,  3.9232e-02,  9.0389e-02, -9.0098e-02,
                        7.6410e-02, -4.5344e-02,  1.4145

In [40]:
input = torch.ones(1,784)
net(input)

tensor([[ 0.0740, -0.5930, -0.2624,  0.0965, -0.2836,  0.0191, -0.0337, -0.2314,
         -0.1131,  0.4927]], grad_fn=<MmBackward>)

## References

1. https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

2. Deep Learning, Goodfellow, I., Bengio, Y., Courville A.

3. Programming PyTorch for Deep Learning, Pointer, I.